### ISSUE TITLE
Redirection of stdin results in panic on unrwrap()

### ISSUE THREAD

**Issue by OdysseusGE** [MovingtoMars/liner#77]
For example  `echo foo | ./target/debug/liner_test` gives:
>thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 25, kind: Other, message: "Inappropriate ioctl for device" }', libcore/result.rs:916:5

The problematic unwrap is at src/context.rs:95, which calls `let stdout = stdout().into_raw_mode().unwrap();`

This issue also causes redox-os/ion to panic with a redirected stdin.
See also: https://github.com/ticki/termion/issues/39

**Comment by P-E-Meunier** [comment]
We're having the same problem on Pijul.
